# Generated by Django 3.0.6 on 2020-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200526_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='money_gel',
            new_name='money',
        ),
        migrations.RemoveField(
            model_name='card',
            name='money_eur',
        ),
        migrations.RemoveField(
            model_name='card',
            name='money_usd',
        ),
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(default='8194625970', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='number1',
            field=models.CharField(default='2863704928', max_length=10),
        ),
    ]
