# Generated by Django 3.0.6 on 2020-05-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200516_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(default='1908406481', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.FloatField(default=10),
        ),
    ]
