# Generated by Django 3.0.6 on 2020-05-17 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200516_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sentMoney',
            new_name='sent_money',
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_sent',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(default='3597810670', max_length=10),
        ),
    ]
