# Generated by Django 3.0.6 on 2020-05-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200517_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(default='3610678202', max_length=10),
        ),
    ]
