# Generated by Django 3.1.1 on 2020-09-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200526_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(default='8280747526', max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(default='7928562650', max_length=10),
        ),
    ]
